apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-spy
  namespace: default
  labels:
    name: influxdb-spy
spec:
  selector:
    matchLabels:
      name: influxdb-spy
  template:
    metadata:
      labels:
        name: influxdb-spy
    spec:
      containers:
      - name: influxdb-spy
        image: influxdb:alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: INFLUXDB_DB
          value: spy
        - name: INFLUXDB_WRITE_USER
          value: kubespy
        - name: INFLUXDB_WRITE_USER_PASSWORD
          value: kubespy
        - name: INFLUXDB_READ_USER
          value: grafana
        - name: INFLUXDB_READ_USER_PASSWORD
          value: grafana
        volumeMounts:
        - name: host-time
          mountPath: /etc/localtime
      volumes:
      - name: host-time
        hostPath:
          path: /etc/localtime

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-spy
  namespace: default
  labels:
    name: influxdb-spy
spec:
  selector:
    name: influxdb-spy
  ports:
  - port: 8086
